# config/packages/cors.yaml
nelmio_cors:
    paths:
        '^/':
            allow_origin: ['*']
            allow_methods: ['GET', 'POST', 'PUT', 'DELETE']
            allow_headers: ['*']
            max_age: 3600
