image: php:8.2

services:
  - mysql:5.7

variables:
  MYSQL_ROOT_PASSWORD: root
  MYSQL_DATABASE: symfony
  MYSQL_USER: symfony
  MYSQL_PASSWORD: symfony

cache:
  paths:
    - vendor/
    - .cache/

before_script:
  - apt-get update
  - apt-get install -y unzip git libicu-dev libpq-dev libzip-dev
  - docker-php-ext-install intl pdo pdo_mysql zip
  - composer install

stages:
  - test
  - security
  - deploy

# SAST (Static Application Security Testing) configuration
sast:
  stage: security
  script:
    - echo "Running Static Application Security Testing"
  include:
    - template: Security/SAST.gitlab-ci.yml

test:
  stage: test
  script:
    - php bin/console doctrine:database:create --if-not-exists
    - php bin/console doctrine:schema:create
    - ./bin/phpunit
  artifacts:
    paths:
      - var/logs/
    reports:
      junit: var/logs/junit.xml

deploy:
  stage: deploy
  script:
    - echo "Deploy to production server"
  only:
    - main
