image: php:8.2

variables:
  MYSQL_HOST: mysql
  MYSQL_PORT: 3306
  MYSQL_DATABASE: example_db
  MYSQL_USER: yassine
  MYSQL_PASSWORD: yassine
  MYSQL_ROOT_PASSWORD: my-secret-pw
  SYMFONY_ENV: test

stages:
  - build
  - test

before_script:
  - apt-get update && apt-get install -y \
      git \
      unzip \
      libzip-dev \
      zlib1g-dev \
      libicu-dev \
      libpng-dev \
      libjpeg-dev \
      libfreetype6-dev \
      libldap2-dev \
      libxml2-dev \
      libpq-dev \
      libonig-dev \
      curl \
      && rm -rf /var/lib/apt/lists/* \
      && docker-php-ext-configure gd --with-freetype --with-jpeg \
      && docker-php-ext-install gd intl pdo pdo_mysql pdo_pgsql opcache zip ldap soap \
      && curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer

build:
  stage: build
  script:
    - composer install --prefer-dist --no-scripts --no-interaction --no-progress --no-suggest --optimize-autoloader
  only:
    - main
    - develop

test:
  stage: test
  script:
    - vendor/bin/phpunit
  only:
    - merge_requests
    - main
    - develop

code_quality:
  stage: test
  script:
    - vendor/bin/phpstan analyse src --level=max
  only:
    - merge_requests
    - main
    - develop
  allow_failure: true

cache:
  paths:
    - vendor/
    - var/
