image: php:8.2

variables:
  APP_ENV: test
  DATABASE_URL: mysql://root:Ysy9%3F9yaai@127.0.0.1:3306/coupac

stages:
  - build
  - sast
  - test

before_script:
  - apt-get update
  - apt-get install -y libzip-dev libicu-dev libpng-dev libjpeg-dev libfreetype6-dev libldap2-dev libxml2-dev libpq-dev libonig-dev unzip curl git
  - docker-php-ext-configure gd --with-freetype --with-jpeg
  - docker-php-ext-install gd intl pdo pdo_mysql pdo_pgsql opcache zip ldap soap
  - pecl install mongodb
  - docker-php-ext-enable mongodb
  - curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
  - composer install --prefer-dist --no-scripts --no-autoloader

build:
  stage: build
  script:
    - composer install --prefer-dist --no-scripts --no-interaction --no-progress --no-suggest --optimize-autoloader
  only:
    - main
    - develop

sast:
  stage: sast
  script:
    - curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
    - composer config minimum-stability dev
    - composer config prefer-stable true
    - composer require --dev roave/security-advisories
    - vendor/bin/security-checker security:check
  only:
    - merge_requests
    - main
    - develop

test:
  stage: test
  script:
    - php bin/console doctrine:database:create --if-not-exists --env=test
    - php bin/console doctrine:schema:update --force --env=test
    - vendor/bin/phpunit
  only:
    - main
    - develop
