image: php:8.2

variables:
  MYSQL_HOST: localhost
  MYSQL_PORT: 3306
  MYSQL_DATABASE: coupac
  MYSQL_USER: root
  MYSQL_PASSWORD: Ysy9?9yaai 
  MYSQL_ROOT_PASSWORD: Ysy9?9yaai 
  SYMFONY_ENV: coupac




stages:
  - build
  - analyze
  - deploy

before_script:
  - apt-get update
  - apt-get install -y libzip-dev libicu-dev libpng-dev libjpeg-dev libfreetype6-dev libldap2-dev libxml2-dev libpq-dev libonig-dev unzip curl git
  - docker-php-ext-configure gd --with-freetype --with-jpeg
  - docker-php-ext-install gd intl pdo pdo_mysql pdo_pgsql opcache zip ldap soap
  - pecl install mongodb
  - docker-php-ext-enable mongodb
  - curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
  - composer install --prefer-dist --no-scripts --no-autoloader

build:
  stage: build
  script:
    - composer install --prefer-dist --no-scripts --no-interaction --no-progress --no-suggest --optimize-autoloader
  only:
    - main
    - develop

analyze:
  stage: analyze
  script:
    - curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
    - composer require --dev phpstan/phpstan
    - vendor/bin/phpstan analyse src --level max
  only:
    - merge_requests
    - main
    - develop

deploy:
  stage: deploy
  script:
    - ./deploy.sh
  only:
    - main
